#!/command/with-contenv bash

TZ=${TZ:-America/New_York}

echo "Setting timezone to $TZ"

if [ ! -f /etc/timezone ] || ! grep -q "$TZ" /etc/timezone; then
  echo "$TZ" > /etc/timezone
  ln -sf "/usr/share/zoneinfo/$TZ" /etc/localtime
fi