name: Build k8s-alpine-baseimage

env:
#  PRJDIR: "k8s-alpine-baseimage"
#  IMGNAME: "k8s-alpine-baseimage"
  DOCKER_OWNER: "nforceroh"

on:
  push:

jobs:
  deploy-docker-image:
    runs-on: arc-k8s-alpine-baseimage
    steps:
      - name: Get repo name
        run: |
          echo "${{ github.repository }}" | cut -d "/" -f 2 > repo.txt
          echo "REPO_NAME=$(cat repo.txt)" >> $GITHUB_ENV
          rm -rf repo.txt

      - run: echo "Starting build for ${{ env.REPO_NAME }}"

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set build date
        id: date
        run: echo "::set-output name=builddate::$(date +'%Y%m%d%H%M%S')"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ env.DOCKER_OWNER }}/${{ env.REPO_NAME }}:${{ steps.date.outputs.builddate }}
            ${{ env.DOCKER_OWNER }}/${{ env.REPO_NAME }}:latest
          build-args: |
            BUILD_DATE=${{ steps.date.outputs.builddate }}
            VERSION=${{ steps.date.outputs.builddate }}
