name: Docker Image for GHCR

on:
  push:

jobs:
  deploy-docker-image:
    runs-on: arc-k8s-alpine-baseimage
    steps:
      - name: Get repo name
        run: echo "IMAGE_NAME=$(echo ${{ github.repository }} | cut -d "/" -f 2)" >> $GITHUB_ENV
      - name: Set build date
        id: date
        run: echo "BUILD_DATE=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      - name: Variables defined
        run: |
          echo "IMAGE_NAME  = ${{ env.REPO_NAME }}"
          echo "BUILD_DATE   = ${{ env.BUILD_DATE }}"
          echo "github.actor = ${{ github.actor }}"
      - run: echo "Starting build for ${{ github.repository }}"
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}     

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}:${{ env.BUILD_DATE }}
            ghcr.io/${{ env.IMAGE_NAME }}:latest
          build-args: |
            BUILD_DATE=${{ env.BUILD_DATE }}
            VERSION=${{ env.BUILD_DATE }}
